version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - ${DB_PORT:-5432}:5432
  bot:
    image: ghcr.io/johnspade/tasko_bot:0.0.0-109-91c1c725-20230323-2127
    depends_on: 
      - db
    ports:
      - ${PORT:-8080}:8080
    environment:
      - BOT_TOKEN
      - BOT_EXTERNAL_URL
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks
