version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - ${DB_PORT:-5432}:5432
